# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- default

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1  
  displayName: 'Install NuGet'

- task: NuGetCommand@2 
  displayName: 'NuGet Restore'
  condition: succeeded()
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build API'
  condition: succeeded()
  inputs:
    command: 'build'
    projects: '**/Uceme.API.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build UI'
  condition: succeeded()
  inputs:
    command: 'build'
    projects: '**/Uceme.UI.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  condition: succeeded()
  inputs:
    command: 'test'
    projects: '**/*.Test.csproj'

- task: NodeTool@0
  displayName: 'Install node'
  condition: succeeded()
  inputs:
    versionSpec: '16.x'
    checkLatest: true

- task: Npm@1
  displayName: 'npm install'
  condition: succeeded()
  inputs:
    command: 'install'
    workingDir: 'src/Uceme.UI/ClientApp'

- task: Npm@1
  displayName: 'npm build'
  condition: succeeded()
  inputs:
    command: 'custom'
    workingDir: 'src/Uceme.UI/ClientApp'
    customCommand: 'run build'

#- task: Npm@1
#  displayName: 'npm test'
#  condition: succeededOrFailed() 
#  inputs:
#    command: 'custom'
#    workingDir: 'src/Uceme.UI/ClientApp'
#    customCommand: 'run test:coverage'
