# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- default

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Uceme.API.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Uceme.UI.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*.Test.csproj'

- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
    checkLatest: true

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'src/Uceme.UI/ClientApp'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'src/Uceme.UI/ClientApp'
    customCommand: 'run build'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'src/Uceme.UI/ClientApp'
    customCommand: 'run test:coverage'

