# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master
- default
- dev
- develop

pr:
- master
- default
- dev
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  APIprojects: '**/Uceme.API.csproj'
  UIprojects: '**/Uceme.UI.csproj'

steps:

- task: DotNetCoreCLI@2
  displayName: 'Build API'
  inputs:
    command: 'build'
    projects: '$(APIprojects)'
    configuration: '$(buildConfiguraton)'

- task: DotNetCoreCLI@2
  displayName: 'Build UI'
  inputs:
    command: 'build'
    projects: '$(UIprojects)'
    configuration: '$(buildConfiguraton)'

# - task: DotNetCoreCLI@2
#   displayName: 'Run unit tests'
#   inputs:
#     command: 'test'
#     projects: |
#       **/**.[Tt]ests.csproj
#       !**/*.[Ii]ntegration.[Tt]ests/**.csproj
#     testRunTitle: 'Run Unit Tests'
#     arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura'
#     publishTestResults: true
  
# - task: PublishCodeCoverageResults@1
#   displayName: 'Publish code coverage report'
#   inputs:
#     codeCoverageTool: 'Cobertura'
#     summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

# - task: NodeTool@0
#   displayName: 'Install node'
#   condition: succeeded()
#   inputs:
#     versionSpec: '16.x'
#     checkLatest: true

# - task: Npm@1
#   displayName: 'npm install'
#   condition: succeeded()
#   inputs:
#     command: 'install'
#     workingDir: 'src/Uceme.UI/ClientApp'

# - task: Npm@1
#   displayName: 'npm build'
#   condition: succeeded()
#   inputs:
#     command: 'custom'
#     workingDir: 'src/Uceme.UI/ClientApp'
#     customCommand: 'run build'

#- task: Npm@1
#  displayName: 'npm test'
#  condition: succeededOrFailed() 
#  inputs:
#    command: 'custom'
#    workingDir: 'src/Uceme.UI/ClientApp'
#    customCommand: 'run test:coverage'
