apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-08-24T20:04:24Z"
  generation: 1
  labels:
    app: uceme-api
  name: uceme-api
  namespace: default
  resourceVersion: "24117"
  uid: f96c0a96-ab07-4a1c-9822-3336e5079bc0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: uceme-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: uceme-api
    spec:
      containers:
      - image: localhost:50000/ucemeapi
        imagePullPolicy: Never
        name: ucemeapi
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
