//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uceme.Model.Models
{
    using System.ComponentModel.DataAnnotations;

    public partial class PaginaAmiga
    {
        [Key]
        public int idPagina { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string link { get; set; }
        public string icono { get; set; }
    }
}
