//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uceme.Model.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class Tecnica
    {
        [Key]
        public int idTecnica { get; set; }
        public string titulo { get; set; }
        public DateTime fecha { get; set; }
        public string foto { get; set; }
        public string texto { get; set; }
    }
}
