//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uceme.Model.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [Key]
        public int idUsuario { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string nick { get; set; }
        public string login { get; set; }
        public string foto { get; set; }
        public Nullable<System.DateTime> ultimoupdate { get; set; }
        public string password { get; set; }
        public Nullable<bool> newsletter { get; set; }
        public string linkedin { get; set; }
        public Nullable<int> display_order { get; set; }
    
        public ICollection<Blog> Blog { get; set; }
        public ICollection<Documento> Documento { get; set; }

        public int idCurriculum { get; set; }
        ////public virtual Curriculum Curriculum { get; set; }
        public int idDatosContacto { get; set; }
        ////public virtual DatosContacto DatosContacto { get; set; }
        public int idRol { get; set; }
        public Rol Rol { get; set; }
    }
}
