//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uceme.Model.Models
{
    public partial class webpages_UsersInRoles
    {
        public webpages_UsersInRoles()
        {
        }
    
        public int RoleId { get; set; }
        public int UserId { get; set; }
    }
}
