version: "3.8"
services:
    db:
        image: "mcr.microsoft.com/azure-sql-edge"
        environment:
            SA_PASSWORD: "Ch4mp10ns"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433
        volumes:
            - sqlucemedata:/var/opt/mssql
        restart: always
        container_name: DockerUcemeDb
volumes:
    sqlucemedata:
