version: "3.8"
services:
    db:
        image: "mcr.microsoft.com/azure-sql-edge"
        environment:
            SA_PASSWORD: "Ch4mp10ns"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - sqlucemedata:/var/opt/mssql
        restart: always
        container_name: DockerUcemeDb
    ucemeapi:
        image: "ucemeapi"
        ports:
            - "32371:80"
        restart: always
        environment:
              ConnectionStrings__UcemeConnection: "data source=db;initial catalog=UCEMEDb;user id=sa;password=Ch4mp10ns;MultipleActiveResultSets=True;"
        depends_on:
            - db
        container_name: ucemeapi
volumes:
    sqlucemedata:
