version: "3.8"
services:
    ucemeDb2:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        command: bash -c "
                chmod +x /opt/mssql_scripts/run-initialization.sh
                && /opt/mssql_scripts/run-initialization.sh"
        stdin_open: true
        environment:
            SA_PASSWORD: "Ch4mp10ns"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        restart: always
        container_name: DockerUcemeDb22
        networks:
            - db_net
        volumes:
            - ./mssql_scripts:/opt/mssql_scripts
            - ./sqlucemedata:/var/opt/mssql
networks:
    db_net:
        name: db_net
