USE [master]
GO

/****** Object:  Database [UCEMEDb]    Script Date: 15/05/2020 17:26:02 ******/
CREATE DATABASE [UCEMEDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UCEMEDb_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.JA6IUO6\MSSQL\DATA\UCEMEDbClone.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'UCEMEDb_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.JA6IUO6\MSSQL\DATA\UCEMEDbClone.ldf' , SIZE = 2816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UCEMEDb].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [UCEMEDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UCEMEDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UCEMEDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UCEMEDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UCEMEDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [UCEMEDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UCEMEDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UCEMEDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UCEMEDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UCEMEDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UCEMEDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UCEMEDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UCEMEDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UCEMEDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UCEMEDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UCEMEDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UCEMEDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UCEMEDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UCEMEDb] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [UCEMEDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UCEMEDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [UCEMEDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UCEMEDb] SET RECOVERY FULL 
GO

ALTER DATABASE [UCEMEDb] SET  MULTI_USER 
GO

ALTER DATABASE [UCEMEDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UCEMEDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UCEMEDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UCEMEDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [UCEMEDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [UCEMEDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [UCEMEDb] SET  READ_WRITE 
GO

