//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCEME.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tecnica
    {
        public int idTecnica { get; set; }
        public string titulo { get; set; }
        public System.DateTime fecha { get; set; }
        public string foto { get; set; }
        public string texto { get; set; }
    }
}
