//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uceme.Model.Models
{
    using System.Text.Json.Serialization;

    public partial class Appointment
    {
        [JsonPropertyName("idCita")]
        public int idCita { get; set; }

        [JsonPropertyName("dia")]
        public int dia { get; set; }

        [JsonPropertyName("hora")]
        public decimal hora { get; set; }

        [JsonPropertyName("nombre")]
        public string nombre { get; set; }

        [JsonPropertyName("email")]
        public string email { get; set; }

        [JsonPropertyName("telefono")]
        public string telefono { get; set; }

        [JsonPropertyName("idTurno")]
        public int idTurno { get; set; }

        [JsonPropertyName("speciality")]
        public string speciality { get; set; }
    }
}
