//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uceme.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public string titulo { get; set; }
        public string descripcion { get; set; }
        public string link { get; set; }
        public int idVideo { get; set; }
        public Nullable<int> posicion { get; set; }
    }
}
