name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.0

    - name: Create folder
      run: |
          mkdir -p /home/runner/coverage

    - name: Setup .NET
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore src/UCEME.sln

    - name: Build
      run: dotnet build --no-restore src/UCEME.sln

    - name: Test
      run: dotnet test --no-build --verbosity normal src/UCEME.sln --filter TestCategory=MockTests --collect:"XPlat Code Coverage" --logger trx --results-directory ./coverage

    - name: List
      run: ls /home/runner/work/uceme/uceme/coverage/**/coverage.cobertura.xml

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage/**/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '0 50'

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Write to Job Summary
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
