name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.0.0
      with:
        dotnet-version: 6.0.301
    - name: Restore dependencies
      run: dotnet restore src/UCEME.sln
    - name: Build
      run: dotnet build --no-restore src/UCEME.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal src/UCEME.sln --filter TestCategory=MockTests
